; Datos.clp
; Problema del Transporte
; Programación Genética Basada en Reglas
; Master Universitario en Lógica Programación e Inteligencia Artificial
; Universidad de Sevilla
;============================================================================

(deffacts datos-iniciales
        (nElementos 8)
        (nIteraciones 1)
        (cociente-mutacion 50)
        (inicio)
        (p 10)
        (SCC)
        (esfuerzo (ciudadA 0) (ciudadB 1) (esfuerzo 10))
        (esfuerzo (ciudadA 0) (ciudadB 2) (esfuerzo 0))
        (esfuerzo (ciudadA 0) (ciudadB 3) (esfuerzo 20))
        (esfuerzo (ciudadA 0) (ciudadB 4) (esfuerzo 11))
        (esfuerzo (ciudadA 0) (ciudadB 5) (esfuerzo 12))
        (esfuerzo (ciudadA 0) (ciudadB 6) (esfuerzo 7))
        (esfuerzo (ciudadA 0) (ciudadB 7) (esfuerzo 9))
        (esfuerzo (ciudadA 0) (ciudadB 8) (esfuerzo 20))
        (esfuerzo (ciudadA 0) (ciudadB 9) (esfuerzo 0))
        (esfuerzo (ciudadA 1) (ciudadB 2) (esfuerzo 0))
        (esfuerzo (ciudadA 1) (ciudadB 3) (esfuerzo 20))
        (esfuerzo (ciudadA 1) (ciudadB 4) (esfuerzo 11))
        (esfuerzo (ciudadA 1) (ciudadB 5) (esfuerzo 12))
        (esfuerzo (ciudadA 1) (ciudadB 6) (esfuerzo 7))
        (esfuerzo (ciudadA 1) (ciudadB 7) (esfuerzo 9))
        (esfuerzo (ciudadA 1) (ciudadB 8) (esfuerzo 20))
        (esfuerzo (ciudadA 1) (ciudadB 9) (esfuerzo 0))
        (esfuerzo (ciudadA 2) (ciudadB 3) (esfuerzo 20))
        (esfuerzo (ciudadA 2) (ciudadB 4) (esfuerzo 11))
        (esfuerzo (ciudadA 2) (ciudadB 5) (esfuerzo 12))
        (esfuerzo (ciudadA 2) (ciudadB 6) (esfuerzo 7))
        (esfuerzo (ciudadA 2) (ciudadB 7) (esfuerzo 9))
        (esfuerzo (ciudadA 2) (ciudadB 8) (esfuerzo 20))
        (esfuerzo (ciudadA 2) (ciudadB 9) (esfuerzo 0))
        (esfuerzo (ciudadA 3) (ciudadB 4) (esfuerzo 11))
        (esfuerzo (ciudadA 3) (ciudadB 5) (esfuerzo 12))
        (esfuerzo (ciudadA 3) (ciudadB 6) (esfuerzo 7))
        (esfuerzo (ciudadA 3) (ciudadB 7) (esfuerzo 9))
        (esfuerzo (ciudadA 3) (ciudadB 8) (esfuerzo 20))
        (esfuerzo (ciudadA 3) (ciudadB 9) (esfuerzo 0))
        (esfuerzo (ciudadA 4) (ciudadB 5) (esfuerzo 12))
        (esfuerzo (ciudadA 4) (ciudadB 6) (esfuerzo 7))
        (esfuerzo (ciudadA 4) (ciudadB 7) (esfuerzo 9))
        (esfuerzo (ciudadA 4) (ciudadB 8) (esfuerzo 20))
        (esfuerzo (ciudadA 4) (ciudadB 9) (esfuerzo 0))
        (esfuerzo (ciudadA 5) (ciudadB 6) (esfuerzo 7))
        (esfuerzo (ciudadA 5) (ciudadB 7) (esfuerzo 9))
        (esfuerzo (ciudadA 5) (ciudadB 8) (esfuerzo 20))
        (esfuerzo (ciudadA 5) (ciudadB 9) (esfuerzo 0))
        (esfuerzo (ciudadA 6) (ciudadB 7) (esfuerzo 8))
        (esfuerzo (ciudadA 6) (ciudadB 8) (esfuerzo 1))
        (esfuerzo (ciudadA 6) (ciudadB 9) (esfuerzo 3))
        (esfuerzo (ciudadA 7) (ciudadB 8) (esfuerzo 20))
        (esfuerzo (ciudadA 7) (ciudadB 9) (esfuerzo 14))
        (esfuerzo (ciudadA 8) (ciudadB 9) (esfuerzo 7))
)
